/**
 * Copy the PDFium WASM binary into `public/` so it is fetched at runtime
 * rather than bundled.
 *
 * Fetching an explicit path from `public/` is the one approach that behaves
 * identically under Turbopack, under `--webpack`, and under `output: 'export'`.
 * Importing the `.wasm` through the bundler does not.
 *
 * The copy is gitignored and regenerated by `pnpm sync:wasm`, which `predev`
 * and `prebuild` both run, so the binary always matches the installed package.
 */
import { copyFile, mkdir, readFile, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';

const require = createRequire(import.meta.url);

const src = require.resolve('@embedpdf/pdfium/pdfium.wasm');
const outDir = join(process.cwd(), 'public', 'pdfium');
const dest = join(outDir, 'pdfium.wasm');

await mkdir(outDir, { recursive: true });
await copyFile(src, dest);

// Record the version alongside it. A stale binary paired with fresh bindings
// fails as a missing-export error deep inside a cwrap call, which is a
// miserable thing to debug; this makes the mismatch visible instead.
const pkgPath = join(dirname(require.resolve('@embedpdf/pdfium')), '..', 'package.json');
let version = 'unknown';
try {
  version = JSON.parse(await readFile(pkgPath, 'utf8')).version ?? 'unknown';
} catch {
  // Layout differs between package managers; the version file is a nicety.
}
await writeFile(join(outDir, 'version.json'), JSON.stringify({ version }, null, 2) + '\n');

const { size } = await import('node:fs').then((fs) => fs.promises.stat(dest));
console.log(`pdfium.wasm ${version} → public/pdfium/ (${(size / 1024 / 1024).toFixed(2)} MB)`);
